/**
 * "*" = All tags
 * "-" = Not supported in HTML 5. Use CSS instead
 * 
 * Tools:
 * - https://csvjson.com/csv2json
 * - https://tableconvert.com/html-to-excel
 * 
 * Refs: https://www.w3schools.com/tags/ref_attributes.asp
 * 
 * Copyright 2022, Indra Gunawan <indra.sync@gmail.com>
 */

/*
const attributes: Record<string, string> = {
  "accept": "input",
  "accept-charset": "form",
  "accesskey": "*",
  "action": "form",
  "align": "-",
  "alt": "area, img, input",
  "async": "script",
  "autocomplete": "form, input",
  "autofocus": "button, input, select, textarea",
  "autoplay": "audio, video",
  "bgcolor": "-",
  "border": "-",
  "charset": "meta, script",
  "checked": "input",
  "cite": "blockquote, del, ins, q",
  "class": "*",
  "color": "-",
  "cols": "textarea",
  "colspan": "td, th",
  "content": "meta",
  "contenteditable": "*",
  "controls": "audio, video",
  "coords": "area",
  "data": "object",
  "data-": "*",
  "datetime": "del, ins, time",
  "default": "track",
  "defer": "script",
  "dir": "*",
  "dirname": "input, textarea",
  "disabled": "button, fieldset, input, optgroup, option, select,  textarea",
  "download": "a, area",
  "draggable": "*",
  "enctype": "form",
  "for": "label, output",
  "form": "button, fieldset, input, label, meter, object,  output, select, textarea",
  "formaction": "button, input",
  "headers": "td, th",
  "height": "canvas, embed, iframe, img, input, object, video",
  "hidden": "*",
  "high": "meter",
  "href": "a, area, base, link",
  "hreflang": "a, area, link",
  "http-equiv": "meta",
  "id": "*",
  "ismap": "img",
  "kind": "track",
  "label": "track, option, optgroup",
  "lang": "*",
  "list": "input",
  "loop": "audio, video",
  "low": "meter",
  "max": "input, meter, progress",
  "maxlength": "input, textarea",
  "media": "a, area, link, source, style",
  "method": "form",
  "min": "input, meter",
  "multiple": "input, select",
  "muted": "video, audio",
  "name": "button, fieldset, form, iframe, input, map, meta,  object, output, param, select, textarea",
  "novalidate": "form",
  "onabort": "audio, embed, img, object, video",
  "onafterprint": "body",
  "onbeforeprint": "body",
  "onbeforeunload": "body",
  "onblur": "*",
  "oncanplay": "audio, embed, object, video",
  "oncanplaythrough": "audio, video",
  "onchange": "*",
  "onclick": "*",
  "oncontextmenu": "*",
  "oncopy": "*",
  "oncuechange": "track",
  "oncut": "*",
  "ondblclick": "*",
  "ondrag": "*",
  "ondragend": "*",
  "ondragenter": "*",
  "ondragleave": "*",
  "ondragover": "*",
  "ondragstart": "*",
  "ondrop": "*",
  "ondurationchange": "audio, video",
  "onemptied": "audio, video",
  "onended": "audio, video",
  "onerror": "audio, body, embed, img, object, script, style, video",
  "onfocus": "*",
  "onhashchange": "body",
  "oninput": "*",
  "oninvalid": "*",
  "onkeydown": "*",
  "onkeypress": "*",
  "onkeyup": "*",
  "onload": "body, iframe, img, input, link, script, style",
  "onloadeddata": "audio, video",
  "onloadedmetadata": "audio, video",
  "onloadstart": "audio, video",
  "onmousedown": "*",
  "onmousemove": "*",
  "onmouseout": "*",
  "onmouseover": "*",
  "onmouseup": "*",
  "onmousewheel": "*",
  "onoffline": "body",
  "ononline": "body",
  "onpagehide": "body",
  "onpageshow": "body",
  "onpaste": "*",
  "onpause": "audio, video",
  "onplay": "audio, video",
  "onplaying": "audio, video",
  "onpopstate": "body",
  "onprogress": "audio, video",
  "onratechange": "audio, video",
  "onreset": "form",
  "onresize": "body",
  "onscroll": "*",
  "onsearch": "input",
  "onseeked": "audio, video",
  "onseeking": "audio, video",
  "onselect": "*",
  "onstalled": "audio, video",
  "onstorage": "body",
  "onsubmit": "form",
  "onsuspend": "audio, video",
  "ontimeupdate": "audio, video",
  "ontoggle": "details",
  "onunload": "body",
  "onvolumechange": "audio, video",
  "onwaiting": "audio, video",
  "onwheel": "*",
  "open": "details",
  "optimum": "meter",
  "pattern": "input",
  "placeholder": "input, textarea",
  "poster": "video",
  "preload": "audio, video",
  "readonly": "input, textarea",
  "rel": "a, area,  form, link",
  "required": "input, select, textarea",
  "reversed": "ol",
  "rows": "textarea",
  "rowspan": "td, th",
  "sandbox": "iframe",
  "scope": "th",
  "selected": "option",
  "shape": "area",
  "size": "input, select",
  "sizes": "img, link, source",
  "span": "col, colgroup",
  "spellcheck": "*",
  "src": "audio, embed, iframe, img, input, script, source, track,  video",
  "srcdoc": "iframe",
  "srclang": "track",
  "srcset": "img, source",
  "start": "ol",
  "step": "input",
  "style": "*",
  "tabindex": "*",
  "target": "a, area, base, form",
  "title": "*",
  "translate": "*",
  "type": "a, button, embed, input, link, menu, object, script,  source, style",
  "usemap": "img, object",
  "value": "button, input, li, option,  meter, progress, param",
  "width": "canvas, embed, iframe, img, input, object, video",
  "wrap": "textarea"
}

const transform = Object.keys(attributes).reduce((acc, key) => {
  acc[key] = attributes[key]
    .split(',')
    .map(tag => tag.trim())
    .reduce((acc, tag) => {
      if (tag !== '-) {
        acc[tag] = true
      }
      return acc
    }, {} as Record<string, boolean>)
  return acc
}, {} as Record<string, Record<string, boolean>>)

console.log(transform)

*/

const attributes: Record<string, Record<string, boolean>> = {
  accept: { input: true },
  "accept-charset": { form: true },
  accesskey: { "*": true },
  action: { form: true },
  align: {},
  alt: { area: true, img: true, input: true },
  async: { script: true },
  autocomplete: { form: true, input: true },
  autofocus: { button: true, input: true, select: true, textarea: true },
  autoplay: { audio: true, video: true },
  bgcolor: {},
  border: {},
  charset: { meta: true, script: true },
  checked: { input: true },
  cite: { blockquote: true, del: true, ins: true, q: true },
  class: { "*": true },
  color: {},
  cols: { textarea: true },
  colspan: { td: true, th: true },
  content: { meta: true },
  contenteditable: { "*": true },
  controls: { audio: true, video: true },
  coords: { area: true },
  data: { object: true },
  "data-": { "*": true },
  datetime: { del: true, ins: true, time: true },
  default: { track: true },
  defer: { script: true },
  dir: { "*": true },
  dirname: { input: true, textarea: true },
  disabled: {
    button: true,
    fieldset: true,
    input: true,
    optgroup: true,
    option: true,
    select: true,
    textarea: true
  },
  download: { a: true, area: true },
  draggable: { "*": true },
  enctype: { form: true },
  for: { label: true, output: true },
  form: {
    button: true,
    fieldset: true,
    input: true,
    label: true,
    meter: true,
    object: true,
    output: true,
    select: true,
    textarea: true
  },
  formaction: { button: true, input: true },
  headers: { td: true, th: true },
  height: {
    canvas: true,
    embed: true,
    iframe: true,
    img: true,
    input: true,
    object: true,
    video: true
  },
  hidden: { "*": true },
  high: { meter: true },
  href: { a: true, area: true, base: true, link: true },
  hreflang: { a: true, area: true, link: true },
  "http-equiv": { meta: true },
  id: { "*": true },
  ismap: { img: true },
  kind: { track: true },
  label: { track: true, option: true, optgroup: true },
  lang: { "*": true },
  list: { input: true },
  loop: { audio: true, video: true },
  low: { meter: true },
  max: { input: true, meter: true, progress: true },
  maxlength: { input: true, textarea: true },
  media: { a: true, area: true, link: true, source: true, style: true },
  method: { form: true },
  min: { input: true, meter: true },
  multiple: { input: true, select: true },
  muted: { video: true, audio: true },
  name: {
    button: true,
    fieldset: true,
    form: true,
    iframe: true,
    input: true,
    map: true,
    meta: true,
    object: true,
    output: true,
    param: true,
    select: true,
    textarea: true
  },
  novalidate: { form: true },
  onabort: { audio: true, embed: true, img: true, object: true, video: true },
  onafterprint: { body: true },
  onbeforeprint: { body: true },
  onbeforeunload: { body: true },
  onblur: { "*": true },
  oncanplay: { audio: true, embed: true, object: true, video: true },
  oncanplaythrough: { audio: true, video: true },
  onchange: { "*": true },
  onclick: { "*": true },
  oncontextmenu: { "*": true },
  oncopy: { "*": true },
  oncuechange: { track: true },
  oncut: { "*": true },
  ondblclick: { "*": true },
  ondrag: { "*": true },
  ondragend: { "*": true },
  ondragenter: { "*": true },
  ondragleave: { "*": true },
  ondragover: { "*": true },
  ondragstart: { "*": true },
  ondrop: { "*": true },
  ondurationchange: { audio: true, video: true },
  onemptied: { audio: true, video: true },
  onended: { audio: true, video: true },
  onerror: {
    audio: true,
    body: true,
    embed: true,
    img: true,
    object: true,
    script: true,
    style: true,
    video: true
  },
  onfocus: { "*": true },
  onhashchange: { body: true },
  oninput: { "*": true },
  oninvalid: { "*": true },
  onkeydown: { "*": true },
  onkeypress: { "*": true },
  onkeyup: { "*": true },
  onload: {
    body: true,
    iframe: true,
    img: true,
    input: true,
    link: true,
    script: true,
    style: true
  },
  onloadeddata: { audio: true, video: true },
  onloadedmetadata: { audio: true, video: true },
  onloadstart: { audio: true, video: true },
  onmousedown: { "*": true },
  onmousemove: { "*": true },
  onmouseout: { "*": true },
  onmouseover: { "*": true },
  onmouseup: { "*": true },
  onmousewheel: { "*": true },
  onoffline: { body: true },
  ononline: { body: true },
  onpagehide: { body: true },
  onpageshow: { body: true },
  onpaste: { "*": true },
  onpause: { audio: true, video: true },
  onplay: { audio: true, video: true },
  onplaying: { audio: true, video: true },
  onpopstate: { body: true },
  onprogress: { audio: true, video: true },
  onratechange: { audio: true, video: true },
  onreset: { form: true },
  onresize: { body: true },
  onscroll: { "*": true },
  onsearch: { input: true },
  onseeked: { audio: true, video: true },
  onseeking: { audio: true, video: true },
  onselect: { "*": true },
  onstalled: { audio: true, video: true },
  onstorage: { body: true },
  onsubmit: { form: true },
  onsuspend: { audio: true, video: true },
  ontimeupdate: { audio: true, video: true },
  ontoggle: { details: true },
  onunload: { body: true },
  onvolumechange: { audio: true, video: true },
  onwaiting: { audio: true, video: true },
  onwheel: { "*": true },
  open: { details: true },
  optimum: { meter: true },
  pattern: { input: true },
  placeholder: { input: true, textarea: true },
  poster: { video: true },
  preload: { audio: true, video: true },
  readonly: { input: true, textarea: true },
  rel: { a: true, area: true, form: true, link: true },
  required: { input: true, select: true, textarea: true },
  reversed: { ol: true },
  rows: { textarea: true },
  rowspan: { td: true, th: true },
  sandbox: { iframe: true },
  scope: { th: true },
  selected: { option: true },
  shape: { area: true },
  size: { input: true, select: true },
  sizes: { img: true, link: true, source: true },
  span: { col: true, colgroup: true },
  spellcheck: { "*": true },
  src: {
    audio: true,
    embed: true,
    iframe: true,
    img: true,
    input: true,
    script: true,
    source: true,
    track: true,
    video: true
  },
  srcdoc: { iframe: true },
  srclang: { track: true },
  srcset: { img: true, source: true },
  start: { ol: true },
  step: { input: true },
  style: { "*": true },
  tabindex: { "*": true },
  target: { a: true, area: true, base: true, form: true },
  title: { "*": true },
  translate: { "*": true },
  type: {
    a: true,
    button: true,
    embed: true,
    input: true,
    link: true,
    menu: true,
    object: true,
    script: true,
    source: true,
    style: true
  },
  usemap: { img: true, object: true },
  value: {
    button: true,
    input: true,
    li: true,
    option: true,
    meter: true,
    progress: true,
    param: true
  },
  width: {
    canvas: true,
    embed: true,
    iframe: true,
    img: true,
    input: true,
    object: true,
    video: true
  },
  wrap: { textarea: true }
}

export function isValidHTMLAttribute(tagName: string, attrName: string): boolean {
  attrName = attrName.substring(0, (attrName.indexOf("-") + 1) || undefined)
  const tags = attributes[attrName]
  return Boolean(tags && (tags['*'] || tags[tagName]))
}

// console.log('isValidHTMLAttribute', isValidHTMLAttribute('div', 'data-nama'))
// console.log('isValidHTMLAttribute', isValidHTMLAttribute('video', 'onerror'))

